<div class="jumbotron">
    <h1><span class="zf-green">New Inventory</span></h1>
    <form action="/inventory/add" method="POST" enctype="multipart/form-data">
        <div class="form-group mt-3">
            <label for="title">Title</label>
            <input name="title" id="title" type="text" class="form-control">
            <?php if (isset($errors['title'])) : ?>
                <?php foreach ($errors['title'] as $errorMessage) : ?>
                    <p class="text-danger text-sm"><?= $errorMessage ?></p>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
        <div class="form-group mt-3">
            <label for="description">Description</label>
            <textarea name="description" id="description" rows="3" class="form-control"></textarea>
            <?php if (isset($errors['description'])) : ?>
                <?php foreach ($errors['description'] as $errorMessage) : ?>
                    <p class="text-danger text-sm"><?= $errorMessage ?></p>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
        <div class="form-group mt-3">
            <label for="qty">Quantity</label>
            <input name="qty" id="qty" type="number" class="form-control">
            <?php if (isset($errors['qty'])) : ?>
                <?php foreach ($errors['qty'] as $errorMessage) : ?>
                    <p class="text-danger text-sm"><?= $errorMessage ?></p>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
        <div class="form-group mt-3">
            <label for="image" class="form-label">Image</label>
            <input name="image" id="image" class="form-control" type="file">
            <?php if (isset($errors['image'])) : ?>
                <?php foreach ($errors['image'] as $errorMessage) : ?>
                    <p class="text-danger text-sm"><?= $errorMessage ?></p>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
        <button type="submit" class="btn btn-primary mt-3">submit</button>
    </form>
</div>
